// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2181.FPU2018.commands;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc2181.FPU2018.Robot;

/**
 *
 */
public class AutoFlippyDoUp extends Command {


	private double m_time;
	private char m_side;

   	public AutoFlippyDoUp(double time, char side) {
    	m_time = time;
        m_side = side;
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
    	setTimeout(m_time);
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
    	if (m_side == 'M' || DriverStation.getInstance().getGameSpecificMessage().charAt(0) == m_side) {
    		Robot.flippyDoo.setPusher(true);
    	}
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
    	if (timeSinceInitialized() >= m_time) {
    		return true;
    	} else
    		return false;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
    	Robot.flippyDoo.setPusher(false);
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    }
}
