// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2181.FPU2018.commands;

import edu.wpi.first.wpilibj.command.CommandGroup;
import org.usfirst.frc2181.FPU2018.subsystems.*;

/**
 *
 */
public class AutoMiddle extends CommandGroup {


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
    public AutoMiddle() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
		
		if(Robot.gameData.charAt(0) == 'L')
		{
			//ADD IN CODE TO FIND VALUES TO BACK UP TO LEFT SWITCH SIDE
			addSequential(new FlipOff(true));
			addSequential(new AutoLeftTurnAround());
			addSequential(new VISCubeGrab());
			if(Robot.gameData.charAt(1) == 'L') 
			{
				addSequential(new AutoSameSideScale());
			} else 
			{
				addSequential(new AutoLToRScale());
			}
		} else 
		{
			//ADD IN CODE TO FIND VALUES TO BACK UP TO RIGHT SWITCH SIDE
			addSequential(new FlipOff(true));
			addSequential(new AutoRightTurnAround());
			addSequential(new VISCubeGrab());
			if(Robot.gameData.charAt(1) == 'R') 
			{
				addSequential(new AutoSameSideScale());
			} else 
			{
				addSequential(new AutoRToLScale());
			}
		}
		//SET LIFT TO BOTTOM
		//BACK UP

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
 
    } 
}
